apiVersion: v2
name: bookshelf-api
description: A production-relevant Bookshelf REST API for Kubernetes learning
type: application
version: 0.1.0
appVersion: "1.0.0"
maintainers:
  - name: ChandraVardhan
